- name: Check if credential already exists
  jenkins_script:
    script: "{{ jenkins_check_credential }}"
    user: "{{ jenkins_admin_user }}"
    password: "{{ jenkins_admin_pass }}"
    args:
      cred_desc: "{{ item.cred_desc }}"
  register: cred_status

- name: Add credential if missing
  jenkins_script:
    script: "{{ jenkins_add_credential }}"
    user: "{{ jenkins_admin_user }}"
    password: "{{ jenkins_admin_pass }}"
    args:
      cred_id: "{{ item.cred_id|default('') }}"
      cred_desc: "{{ item.cred_desc }}"
      cred_user: "{{ item.cred_user }}"
      cred_pass: "{{ item.cred_pass }}"
  changed_when: true
  when: cred_status.output.find("true") == -1
