- name: enable security
  jenkins_script:
    script: "{{ jenkins_configure_security }}"
    args:
        jenkins_admin_user: "{{ jenkins_admin_user }}"
        jenkins_admin_pass: "{{ jenkins_admin_pass }}"
  no_log: True

- name: mark jenkins as secured for future tasks
  set_fact:
    jenkins_secure: yes
